### PR TITLE
use sqlite for tests.. should make it easier to run unit tests for ci

### PR DESCRIPTION
**Pull request by sagehen03**
#### Please check if the PR fulfills these requirements

- [x] The changes don't come from your master branch. ([Source](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)) 

---

#### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
New feature

#### What is the current behavior? (You can also link to an open issue here)
Tests will use a db running in dockerized postgres.  

#### What is the new behavior? (if this is a feature change)
Tests will use sqlite, a file based database that doesn't require additional software installation/set up.

#### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
No

#### Other information
I think this change should make it easier to introduce continuous integration for our rails code.  It also may make it easier for devs to run rails tests locally.

#### Images (before/ after screenshots, interaction GIFs, ...)

---

### CODE REVIEW

**Comment by sagehen03** [comment]
Thanks @emarti43 good catches all around.  I've not been using the docker set up and shame on me for not testing it.  I'm also surprised that sqlite requires a software install in addition to the gem reference, but I must have installed it at some point; maybe via a transitive dependency and forgot that I did or just didn't realize it.  In light of all this, maybe these changes aren't worth it.  Are you on a Mac?  If so, what happens when you run `rails test` from this branch?  I feel like docker works well enough for the folks that are exclusively working in banana-rn, but it would be a slow dev and test cycle if you're working in banana-rails?  Am I missing something; maybe I need to embrace docker more fully.

**Comment by emarti43** [comment]
Yeah, building the image over and over again is a little tedious, so I would see why using it in dev would be a lot better. But I'm not sure if using SQLite in dev/testing and Postgres in prod will create problems in the future.

**Comment by emarti43** [comment]
oh yeah, forgot to mention that I ran these tests both in and out of Docker (on Mac) and worked well with the additional changes I mentioned.

**Comment by sagehen03** [comment]
Doesn't seem like this is worth it and likely a bad idea https://stackoverflow.com/questions/11249059/generic-ruby-solution-for-sqlite3-like-or-postgresql-ilike sorry for the run around!  Docker is potentially a good solution for tests that hit a db in CI that I wasn't considering before.

**Pull request closed without merging**
